### ISSUE TITLE
Incidents should specify time zones

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/status#8] opened 2021-03-21 14:49 UTC
There's no mention of time zones anywhere. Has this been going on for hours or did it just start? Who knows.

**Comment by olblak** [comment] 2021-04-13 07:50
Indeed it assumes UTC, in there is some improvement on the time in the latest version, I'll give a look when I have some time

**Comment by dhruvgupta0503** [comment] 2023-12-28 08:58
hi is this issue still open, i want to work on this issue

**Comment by MarkEWaite** [comment] 2023-12-28 12:59
Yes, the issue is still open.  https://status.jenkins.io/issues/2023-12-27-jira-upgrade/ looks like this (with annotations added)

![screencapture-status-jenkins-io-issues-2023-12-27-jira-upgrade-2023-12-28-05_56_13-edit](https://github.com/jenkins-infra/status/assets/156685/72916640-4f83-4ab1-80b1-0b1503dbe59b)

**Comment by dhruvgupta0503** [comment] 2023-12-30 14:48
can you pls assign this issue to me

**Comment by hervelemeur** [comment] 2023-12-30 15:59
We don't assign issues. Feel free to open a pull request when you're ready.

**Comment by nouralmulhem** [comment] 2024-03-16 13:37
@MarkEWaite is this open for anyone to contribute?
i forked the repo created a branch and ran the submodule command but found that the `issue.html` and `single.html` in the themes are not on the branch i created, then is it not available for open contribution ?

**Comment by MarkEWaite** [comment] 2024-03-16 13:55
> update: oooh this will require modification in the cstate, is it solvable then?

I don't understand why that would not be solvable (though I am open to being proven wrong).  The static page generator is rendering a time from a data file.  The time in the data file is precisely specified (with UTC offset, etc.).  The time shown to the user should be able to include a time zone, even if that time zone is always listed as UTC.  Even better would be for the static page to adjust the page display based on the time zone of the web browser so that users see the time in their local time zone

**Comment by nouralmulhem** [comment] 2024-03-16 14:22
@MarkEWaite had a PR for this

**Comment by MarkEWaite** [comment] 2024-03-16 14:39
Thanks for the pointer to the cState documentation that indicates time zone data in the issue files must be in UTC time.  I had mistakenly created two issues that use my local time zone offset.  My mistake is fixed in:

* #486

**Comment by nouralmulhem** [comment] 2024-03-16 14:49
i think the new versions solves for different time zone as well, however like you mentions the version we have uses UTC time
refer to: https://github.com/cstate/cstate/issues/248

**Comment by MarkEWaite** [comment] 2024-03-16 14:53
> i think the new versions solves for different time zone as well, however like you mentions the version we have uses UTC time refer to: [cstate/cstate#248](https://github.com/cstate/cstate/issues/248)

That's interesting.  When I checked those two items that were written with my local time, they were displayed in my local time on the web pages.  I think we should stay with UTC time in all the issue records for accuracy and worldwide simplicity.

I'm now seeing UTC times on the pages.  Thanks for the improvement.

**Closed by MarkEWaite** 2024-03-16 14:53 UTC
